--
-- insert sample model
--

INSERT INTO T_MODEL_STATE (ID, STATE) VALUES (SEQ_ID_MODEL_STATE.NEXTVAL, 'START');
INSERT INTO T_MODEL_STATE (ID, STATE) VALUES (SEQ_ID_MODEL_STATE.NEXTVAL, 'EMPTY');
INSERT INTO T_MODEL_STATE (ID, STATE) VALUES (SEQ_ID_MODEL_STATE.NEXTVAL, 'SELECT');
INSERT INTO T_MODEL_STATE (ID, STATE) VALUES (SEQ_ID_MODEL_STATE.NEXTVAL, 'CLOSED');
INSERT INTO T_MODEL_STATE (ID, STATE) VALUES (SEQ_ID_MODEL_STATE.NEXTVAL, 'END');

INSERT INTO T_MODEL_EDGE (ID, FROM_ID, TO_ID) VALUES (SEQ_ID_MODEL_EDGE.NEXTVAL, (SELECT ID FROM T_MODEL_STATE WHERE STATE = 'START'), (SELECT ID FROM T_MODEL_STATE WHERE STATE = 'EMPTY'));
INSERT INTO T_MODEL_ACTION (ID, ACTION, TYPE, EDGE_ID) VALUES (SEQ_ID_MODEL_ACTION.NEXTVAL, 'init', 'INTERNAL', SEQ_ID_MODEL_EDGE.CURRVAL);

INSERT INTO T_MODEL_EDGE (ID, FROM_ID, TO_ID) VALUES (SEQ_ID_MODEL_EDGE.NEXTVAL, (SELECT ID FROM T_MODEL_STATE WHERE STATE = 'EMPTY'), (SELECT ID FROM T_MODEL_STATE WHERE STATE = 'SELECT'));
INSERT INTO T_MODEL_ACTION (ID, ACTION, TYPE, EDGE_ID) VALUES (SEQ_ID_MODEL_ACTION.NEXTVAL, 'open', 'PUBLIC', SEQ_ID_MODEL_EDGE.CURRVAL);

INSERT INTO T_MODEL_EDGE (ID, FROM_ID, TO_ID) VALUES (SEQ_ID_MODEL_EDGE.NEXTVAL, (SELECT ID FROM T_MODEL_STATE WHERE STATE = 'SELECT'), (SELECT ID FROM T_MODEL_STATE WHERE STATE = 'CLOSED'));
INSERT INTO T_MODEL_ACTION (ID, ACTION, TYPE, EDGE_ID) VALUES (SEQ_ID_MODEL_ACTION.NEXTVAL, 'complete', 'PUBLIC', SEQ_ID_MODEL_EDGE.CURRVAL);
INSERT INTO T_MODEL_ACTION (ID, ACTION, TYPE, EDGE_ID) VALUES (SEQ_ID_MODEL_ACTION.NEXTVAL, 'finish', 'PUBLIC', SEQ_ID_MODEL_EDGE.CURRVAL);

INSERT INTO T_MODEL_EDGE (ID, FROM_ID, TO_ID) VALUES (SEQ_ID_MODEL_EDGE.NEXTVAL, (SELECT ID FROM T_MODEL_STATE WHERE STATE = 'SELECT'), (SELECT ID FROM T_MODEL_STATE WHERE STATE = 'EMPTY'));
INSERT INTO T_MODEL_ACTION (ID, ACTION, TYPE, EDGE_ID) VALUES (SEQ_ID_MODEL_ACTION.NEXTVAL, 'clear', 'PUBLIC', SEQ_ID_MODEL_EDGE.CURRVAL);

INSERT INTO T_MODEL_EDGE (ID, FROM_ID, TO_ID) VALUES (SEQ_ID_MODEL_EDGE.NEXTVAL, (SELECT ID FROM T_MODEL_STATE WHERE STATE = 'CLOSED'), (SELECT ID FROM T_MODEL_STATE WHERE STATE = 'END'));
INSERT INTO T_MODEL_ACTION (ID, ACTION, TYPE, EDGE_ID) VALUES (SEQ_ID_MODEL_ACTION.NEXTVAL, 'save', 'PUBLIC', SEQ_ID_MODEL_EDGE.CURRVAL);
INSERT INTO T_MODEL_ACTION (ID, ACTION, TYPE, EDGE_ID) VALUES (SEQ_ID_MODEL_ACTION.NEXTVAL, 'stop', 'INTERNAL', SEQ_ID_MODEL_EDGE.CURRVAL);

INSERT INTO T_MODEL_EDGE (ID, FROM_ID, TO_ID) VALUES (SEQ_ID_MODEL_EDGE.NEXTVAL, (SELECT ID FROM T_MODEL_STATE WHERE STATE = 'CLOSED'), (SELECT ID FROM T_MODEL_STATE WHERE STATE = 'SELECT'));
INSERT INTO T_MODEL_ACTION (ID, ACTION, TYPE, EDGE_ID) VALUES (SEQ_ID_MODEL_ACTION.NEXTVAL, 'reopen', 'PUBLIC', SEQ_ID_MODEL_EDGE.CURRVAL);

INSERT INTO T_MODEL_EDGE (ID, FROM_ID, TO_ID) VALUES (SEQ_ID_MODEL_EDGE.NEXTVAL, (SELECT ID FROM T_MODEL_STATE WHERE STATE = 'CLOSED'), (SELECT ID FROM T_MODEL_STATE WHERE STATE = 'EMPTY'));
INSERT INTO T_MODEL_ACTION (ID, ACTION, TYPE, EDGE_ID) VALUES (SEQ_ID_MODEL_ACTION.NEXTVAL, 'drop', 'PUBLIC', SEQ_ID_MODEL_EDGE.CURRVAL);