--
-- Create table for model and process
--

CREATE TABLE T_MODEL_STATE (
  ID BIGINT NOT NULL,
  STATE VARCHAR(60),
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_ID_MODEL_STATE START WITH 1000000 INCREMENT BY 10;


CREATE TABLE T_MODEL_EDGE (
  ID BIGINT NOT NULL,
  FROM_ID BIGINT,
  TO_ID BIGINT,
  PRIMARY KEY (ID)
);

ALTER TABLE T_MODEL_EDGE ADD CONSTRAINT FK_MODEL_EDGE_FROM_STATE
FOREIGN KEY (FROM_ID) REFERENCES T_MODEL_STATE (ID) ON DELETE NO ACTION;

ALTER TABLE T_MODEL_EDGE ADD CONSTRAINT FK_MODEL_EDGE_TO_STATE
FOREIGN KEY (TO_ID) REFERENCES T_MODEL_STATE (ID) ON DELETE NO ACTION;

CREATE SEQUENCE SEQ_ID_MODEL_EDGE START WITH 1000000 INCREMENT BY 10;


CREATE TABLE T_MODEL_ACTION (
  ID BIGINT NOT NULL,
  ACTION VARCHAR(60),
  TYPE VARCHAR(10),
  EDGE_ID BIGINT,
  PRIMARY KEY (ID)
);

ALTER TABLE T_MODEL_ACTION ADD CONSTRAINT FK_MODEL_ACTION_EDGE
FOREIGN KEY (EDGE_ID) REFERENCES T_MODEL_EDGE (ID) ON DELETE NO ACTION;

CREATE SEQUENCE SEQ_ID_MODEL_ACTION START WITH 1000000 INCREMENT BY 10;


CREATE TABLE T_MODEL_GUARD (
  ID BIGINT NOT NULL,
  GUARD VARCHAR(60),
  EDGE_ID BIGINT,
  PRIMARY KEY (ID)
);

ALTER TABLE T_MODEL_GUARD ADD CONSTRAINT FK_MODEL_GUARD_EDGE
FOREIGN KEY (EDGE_ID) REFERENCES T_MODEL_EDGE (ID) ON DELETE NO ACTION;

CREATE SEQUENCE SEQ_ID_MODEL_GUARD START WITH 1000000 INCREMENT BY 10;


CREATE TABLE T_PROCESS_STATE (
  ID BIGINT NOT NULL,
  DOMAINOBJECT_NAME VARCHAR(60),
  DOMAINOBJECT_ID BIGINT,
  PARENT_ID BIGINT,
  STATE_ID BIGINT,
  PRIMARY KEY (ID)
);

ALTER TABLE T_PROCESS_STATE ADD CONSTRAINT FK_PROCESS_STATE_PARENT
FOREIGN KEY (PARENT_ID) REFERENCES T_PROCESS_STATE (ID) ON DELETE NO ACTION;

ALTER TABLE T_PROCESS_STATE ADD CONSTRAINT FK_PROCESS_STATE_MODEL_STATE
FOREIGN KEY (STATE_ID) REFERENCES T_MODEL_STATE (ID) ON DELETE NO ACTION;

CREATE SEQUENCE SEQ_ID_PROCESS_STATE START WITH 1000000 INCREMENT BY 10;

