--
-- Create table for products and special accessories
--

CREATE TABLE T_PRODUCT (
  ID BIGINT NOT NULL,
  CATEGORIE BIGINT,
  COLOR VARCHAR(20),
  DESIRED_DELIVERY DATE,
  PRIMARY KEY (ID)
);

CREATE TABLE T_ACCESSORY (
  ID BIGINT NOT NULL,
  PRODUCT_ID BIGINT,
  SPECIAL SMALLINT NOT NULL,
  DESCRIPTION VARCHAR(60),
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_ID_PRODUCT START WITH 1000000 INCREMENT BY 10;
CREATE SEQUENCE SEQ_ID_ACCESSORY START WITH 1000000 INCREMENT BY 10;
