--
-- Create table for workshops
--

CREATE TABLE T_WORKSHOP (
  ID BIGINT NOT NULL,
  TITLE VARCHAR(100),
  NUMBER DECIMAL(4,0),
  CONTENT VARCHAR(4000),
  DURATION DECIMAL(2,0),
  DAY_OF_EVENT DATE,
  ATTENDANCE DECIMAL(4,0),
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_ID_WORKSHOP START WITH 1000000 INCREMENT BY 10;
